

//   <ul
//   className="chart-data"
//   data-canvas="fund-alocate"
//   data-canvas-type="doughnut"
// >
//   <li
//     data-color="#15216d"
//     data-title="Development"
//     data-amount={40}
//   />
//   <li
//     data-color="#4aa0f6"
//     data-title="Marketing"
//     data-amount={30}
//   />
//   <li
//     data-color="#6ad9ac"
//     data-title="Exchange listing "
//     data-amount={12}
//   />

//   <li
//     data-color="#72a3f4"
//     data-title="Legal"
//     data-amount={8}
//   />
//   <li
//     data-color="#223fa8"
//     data-title="Product"
//     data-amount={7}
//   />

//   <li
//     data-color="#8fa0df"
//     data-title="Operational & Administration"
//     data-amount={3}
//   />
// </ul>

// <ul
// className="chart-data"
// data-canvas="token-alocate"
// data-canvas-type="doughnut"
// >
// <li
//   data-color="#15216d"
//   data-title="Reserve"
//   data-amount={23}
// />
// <li
//   data-color="#15216d"
//   data-title="Rewards"
//   data-amount={14}
// />
// <li
//   data-color="#6ad9ac"
//   data-title="Marketing"
//   data-amount={12}
// />
// <li
//   data-color="#4aa0f6"
//   data-title="Public"
//   data-amount={10}
// />
// <li
//   data-color="#4d6fe9"
//   data-title="Development"
//   data-amount={10}
// />
// <li
//   data-color="#15216d"
//   data-title="Patnership"
//   data-amount={10}
// />
// <li
//   data-color="#8fa0df"
//   data-title="Private"
//   data-amount={8}
// />
// <li
//   data-color="#434564"
//   data-title="Seed"
//   data-amount={7}
// />
// <li
//   data-color="#15216d"
//   data-title="Team"
//   data-amount={6}
// />
// </ul>